services:
  master:
    image: chrislusf/seaweedfs
    ports:
      - "9334:9333"
      - "19334:19333"
    command: "master -ip=master"
    volumes:
      - master_data:/data
    networks:
      - seaweedfs

  volume:
    image: chrislusf/seaweedfs
    ports:
      - "8081:8080"
      - "18081:18080"
    command: 'volume -mserver="master:9333" -port=8080 -ip=volume'
    volumes:
      - volume_data:/data
    networks:
      - seaweedfs
    depends_on:
      - master

  filer:
    image: chrislusf/seaweedfs
    ports:
      - "8889:8888"
    command: 'filer -master="master:9333"'
    volumes:
      - filer_data:/data
    networks:
      - seaweedfs
    depends_on:
      - master
      - volume

volumes:
  master_data:
  volume_data:
  filer_data:

networks:
  seaweedfs:
